#pragma once

// Please don't change the content of this header, it is auto generated by CMAKE

#define PROJECT_SOURCE_DIR "C:/Users/venus/source/repos/Team13-Stranded/A1_A2_stranded_template/template/"
